//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SessionTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SessionTable()
        {
            this.StudentTables = new HashSet<StudentTable>();
        }
    
        public int SessionID { get; set; }
        [Required(ErrorMessage = "Required")]
        [Display(Name = "Session Title:")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Required")]
        [DataType(DataType.Date)]
        public System.DateTime Start_Date { get; set; }
        [Required(ErrorMessage = "Required")]
        [DataType(DataType.Date)]
        public System.DateTime End_Date { get; set; }
        [DataType(DataType.MultilineText)]
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentTable> StudentTables { get; set; }
    }
}
