//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentPromoteTable
    {
        public int StudentPromoteID { get; set; }
        public int StudentID { get; set; }
        public int ProgrammeSemesterID { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ProgrammeSemestersTable ProgrammeSemestersTable { get; set; }
        public virtual StudentTable StudentTable { get; set; }
    }
}
