//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SubjectTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SubjectTable()
        {
            this.SubjectSemesterTables = new HashSet<SubjectSemesterTable>();
        }
    
        public int SubjectID { get; set; }
        [Required(ErrorMessage = "Required")]
        [Display(Name = " Subject Name:")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Required")]
        public double CrHrs { get; set; }
        [Required(ErrorMessage = "Required")]
        public int MidTermTotalMarks { get; set; }
        public int FinalTermTotalMarks { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubjectSemesterTable> SubjectSemesterTables { get; set; }
    }
}
