//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TranscriptDbEntities : DbContext
    {
        public TranscriptDbEntities()
            : base("name=TranscriptDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DepartmentTable> DepartmentTables { get; set; }
        public virtual DbSet<MarkSheetTable> MarkSheetTables { get; set; }
        public virtual DbSet<ProgrammeSemestersTable> ProgrammeSemestersTables { get; set; }
        public virtual DbSet<ProgrammeTable> ProgrammeTables { get; set; }
        public virtual DbSet<SemesterTable> SemesterTables { get; set; }
        public virtual DbSet<SemesterTypeTable> SemesterTypeTables { get; set; }
        public virtual DbSet<SessionTable> SessionTables { get; set; }
        public virtual DbSet<StudentTable> StudentTables { get; set; }
        public virtual DbSet<SubjectSemesterTable> SubjectSemesterTables { get; set; }
        public virtual DbSet<SubjectTable> SubjectTables { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<UsersTable> UsersTables { get; set; }
    }
}
