//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class UsersTable
    {
        public int UserID { get; set; }
        [Required(ErrorMessage = "Required")]
        public string userName { get; set; }
        [Required(ErrorMessage = "Required")]
        public string password { get; set; }
    }
}
